function test_fastsense_widget_event_markers
    root = fileparts(fileparts(mfilename('fullpath')));
    addpath(root); install();
    skipped = { ...
        'testShowEventMarkersDefaultFalse: Plan 1012-03 will wire.', ...
        'testEventStorePropertyDefaultEmpty: Plan 1012-03 will wire.', ...
        'testPropertiesForwardToInnerFastSense: Plan 1012-03 will wire.', ...
        'testToStructOmitsWhenDefault: Plan 1012-03 will wire.', ...
        'testFromStructRehydrates: Plan 1012-03 will wire.', ...
        'testRefreshDiffsLastEventIds: Plan 1012-03 will wire.', ...
        'testRefreshTriggersRerenderOnAdded: Plan 1012-03 will wire.', ...
        'testRefreshTriggersRerenderOnOpenToClosed: Plan 1012-03 will wire.' };
    for i = 1:numel(skipped), fprintf('    SKIP %s\n', skipped{i}); end
    fprintf('    All 0 tests passed (%d skipped pending Plan 1012-03).\n', numel(skipped));
end
