function test_fastsense_event_click
    root = fileparts(fileparts(mfilename('fullpath')));
    addpath(root); install();
    skipped = { ...
        'testPerMarkerButtonDownFcnIsSet: Plan 1012-03 will wire.', ...
        'testUserDataHoldsEventId: Plan 1012-03 will wire.', ...
        'testOpenEventMarkerIsHollow: Plan 1012-03 will wire.', ...
        'testClosedEventMarkerIsFilled: Plan 1012-03 will wire.', ...
        'testClickOpensDetailsPanel: Plan 1012-03 + GUI environment required.', ...
        'testEscDismissesDetailsPanel: Plan 1012-03 + GUI environment required.', ...
        'testXButtonDismissesDetailsPanel: Plan 1012-03 + GUI environment required.', ...
        'testClickOutsideDismissesDetailsPanel: Plan 1012-03 + GUI environment required.' };
    for i = 1:numel(skipped), fprintf('    SKIP %s\n', skipped{i}); end
    fprintf('    All 0 tests passed (%d skipped pending Plan 1012-03).\n', numel(skipped));
end
