function fleets = stressFleets(mode)
%STRESSFLEETS Build stress-test fleet definitions for the industrial plant demo.
%   fleets = stressFleets(mode) returns a struct array describing fleets
%   of synthetic SensorTags grouped onto shared multi-column .dat files.
%
%   These fleets exercise the v3.1 LiveTagPipeline file-major optimization:
%   K files for N tags where K << N. Without them the demo's K=N=10 case
%   doesn't actually stress the file-grouping behavior.
%
%   Modes:
%     'off'    -> empty fleets struct (default — no stress added)
%     'small'  -> pumps fleet only (50 tags / 5 files)
%     'medium' -> pumps + conveyors (150 tags / 6 files)
%     'large'  -> pumps + conveyors + vibration (350 tags / 26 files)
%
%   Returns a struct array, each entry with fields:
%     name      - char fleet name (for logging)
%     prefix    - char tag-key prefix
%     filePat   - char filename pattern with %d slot for bank index
%     nBanks    - scalar number of files (banks)
%     nPerBank  - scalar tags per file (columns)
%     baseFreq  - scalar Hz (signal frequency for variety)
%     baseAmp   - scalar amplitude
%     baseMean  - scalar mean
%     noiseStd  - scalar gaussian noise stddev
%
%   Total tags = nBanks * nPerBank per fleet.
%
%   The shared .dat files are written by writeStressFleetRow_ (called
%   from the writer's per-tick loop) and parsed by LiveTagPipeline via
%   the existing wide-CSV path (RawSource.column = 'pump_0', etc.).
%
%   See also: registerStressFleetTags, writeStressFleetRow_, run_demo.

    if nargin < 1 || isempty(mode)
        mode = 'off';
    end
    if ~ischar(mode)
        error('stressFleets:invalidMode', ...
            'mode must be a char (got %s)', class(mode));
    end

    % Pumps fleet: moderate scale, several banks.
    pumps = struct( ...
        'name',     'pumps', ...
        'prefix',   'pump.bank', ...
        'filePat',  'pump_bank_%d.dat', ...
        'nBanks',   5, ...
        'nPerBank', 10, ...
        'baseFreq', 0.05, ...
        'baseAmp',  2.5, ...
        'baseMean', 4.0, ...
        'noiseStd', 0.10);

    % Conveyors fleet: extreme co-location (1 file, 100 columns).
    conveyors = struct( ...
        'name',     'conveyors', ...
        'prefix',   'conveyor', ...
        'filePat',  'conveyors.dat', ...
        'nBanks',   1, ...
        'nPerBank', 100, ...
        'baseFreq', 0.02, ...
        'baseAmp',  0.5, ...
        'baseMean', 1.5, ...
        'noiseStd', 0.05);

    % Vibration fleet: many tags across many files (high parse cost).
    vibration = struct( ...
        'name',     'vibration', ...
        'prefix',   'vibration.sensor', ...
        'filePat',  'vibration_bank_%d.dat', ...
        'nBanks',   20, ...
        'nPerBank', 10, ...
        'baseFreq', 0.40, ...
        'baseAmp',  0.8, ...
        'baseMean', 0.0, ...
        'noiseStd', 0.20);

    switch lower(mode)
        case 'off'
            fleets = repmat(pumps, 0, 1);  % zero-length struct of same shape
        case 'small'
            fleets = pumps;
        case 'medium'
            fleets = [pumps; conveyors];
        case 'large'
            fleets = [pumps; conveyors; vibration];
        otherwise
            error('stressFleets:unknownMode', ...
                'mode must be one of {off, small, medium, large} (got ''%s'').', mode);
    end
end
