function buildEventsPage(engine, ctx)
%BUILDEVENTSPAGE Populate the Events page.
%   EventTimelineWidget (registry-default EventStore) + fastsense of
%   reactor.pressure (FastSense falls back to TagRegistry.getEventStore()
%   and paints round-marker overlays when events arrive), status widget
%   for the critical monitor, multistatus for all 4 monitors, wrapped in
%   an 'Event Context' group.
%
%   Plan-vs-API notes:
%     - Widget kind 'eventtimeline' is spelled 'timeline' in the
%       WidgetTypeMap_ -> we use 'timeline' at the call site and keep
%       the plan's 'eventtimeline' token in comments.
%     - EventStore is no longer passed explicitly to EventTimelineWidget;
%       the registry-default fallback (TagRegistry.getEventStore) is used.

    reactorPress = TagRegistry.get('reactor.pressure');
    monFeedHi         = TagRegistry.get('feedline.pressure.high');
    monReactorCrit    = TagRegistry.get('reactor.pressure.critical');
    monReactorTempHi  = TagRegistry.get('reactor.temperature.high');
    monCoolingLow     = TagRegistry.get('cooling.flow.low');

    cfg     = plantConfig();
    thPress = cfg.DisplayThresholds.reactor_pressure;

    % ---- Group 'Event Context' wrapping fastsense + eventtimeline ---
    % addWidget('group', 'Label', 'Event Context', ...)
    % InfoText: "Group coupling reactor pressure plot with event stream"
    grp = GroupWidget( ...
        'Label',       'Event Context', ...
        'Mode',        'panel', ...
        'Description', 'Group coupling the reactor.pressure signal with the live event timeline so spikes and events correlate visually.', ...
        'Position',    [1 1 24 8]);

    % addWidget('fastsense', 'Tag', 'reactor.pressure', 'ShowEventMarkers', true, ...)
    % FastSense.renderEventLayer_ checks the bound SensorTag's own EventStore
    % property first, then falls back to TagRegistry.getEventStore() (the
    % registry default set by registerPlantTags via TagRegistry.setEventStore).
    % It does NOT walk the SensorTag's monitor children — events appear here
    % because MonitorTag emits with dual TagKeys {monitor.Key, parent.Key},
    % so EventStore.getEventsForTag('reactor.pressure') finds the markers.
    % See libs/FastSense/FastSense.m renderEventLayer_ + libs/SensorThreshold/MonitorTag.m fireEventsOnRisingEdges_.
    % InfoText: "Reactor pressure with event round markers"
    fsP = FastSenseWidget( ...
        'Title',       'Reactor Pressure with Event Markers', ...
        'Tag',         reactorPress, ...
        'Thresholds',  thPress, ...
        'Description', ['FastSenseWidget | Tag: SensorTag reactor.pressure. ' ...
                        'Threshold from MonitorTag reactor.pressure.critical ' ...
                        '(trip: y > 18 bar). FastSense ShowEventMarkers ' ...
                        'overlays round markers for MonitorTag events.'], ...
        'Position',    [1 1 16 6]);

    % addWidget('eventtimeline', 'FilterTagKey', ...)
    % Real kind is 'timeline'. EventStore is no longer passed explicitly;
    % EventTimelineWidget.resolveEvents_ falls back to TagRegistry.getEventStore()
    % (the registry default set by registerPlantTags via TagRegistry.setEventStore).
    % InfoText: "Live timeline of reactor.pressure.critical events"
    tl = EventTimelineWidget( ...
        'Title',         'Reactor Critical Events', ...
        'FilterTagKey',  'reactor.pressure.critical', ...
        'Description',   ['EventTimelineWidget | EventStore: registry default ' ...
                          '(set by registerPlantTags via TagRegistry.setEventStore). ' ...
                          'Filter: MonitorTag reactor.pressure.critical only.'], ...
        'Position',      [17 1 7 6]);

    grp.addChild(fsP);
    grp.addChild(tl);
    engine.addWidget(grp);

    % ---- Status for reactor.pressure.critical ------------------------
    % InfoText: "Reactor critical monitor indicator"
    engine.addWidget('status', ...
        'Title',       'Reactor Critical', ...
        'Threshold',   'reactor.pressure.critical', ...
        'Description', ['StatusWidget | Tag: MonitorTag reactor.pressure.critical ' ...
                        '(trip: y > 18 bar on SensorTag reactor.pressure).'], ...
        'Position',    [1 9 8 2]);

    % ---- MultiStatus listing all 4 monitors --------------------------
    % InfoText: "All four monitor tags at a glance"
    engine.addWidget('multistatus', ...
        'Title',       'All Plant Monitors', ...
        'Sensors',     {monFeedHi, monReactorCrit, monReactorTempHi, monCoolingLow}, ...
        'Description', ['MultiStatusWidget | Tags: all 4 MonitorTags ' ...
                        '(feedline.pressure.high, reactor.pressure.critical, ' ...
                        'reactor.temperature.high, cooling.flow.low).'], ...
        'Position',    [9 9 16 3]);
end
