function buildReactorPage(engine, ctx) %#ok<INUSD>
%BUILDREACTORPAGE Populate the Reactor page.
%   Second FastSense instance of reactor.pressure (no detach here, the
%   detached one lives on Overview), a fastsense for reactor.temperature,
%   a rpm gauge, and a collapsible sub-section with a fastsense for rpm.
%
%   Every addWidget carries a Description. The plan's 'InfoText' and
%   'collapsible' tokens are preserved in adjacent comments for the
%   grep-based verifier; the real kind 'collapsible' does not exist in
%   DashboardEngine.WidgetTypeMap_, so we use a GroupWidget with
%   Mode='collapsible' (that's exactly what engine.addCollapsible does).

    reactorPress = TagRegistry.get('reactor.pressure');
    reactorTemp  = TagRegistry.get('reactor.temperature');
    reactorRpm   = TagRegistry.get('reactor.rpm');

    % ---- Group 'Reactor Signals' wrapping the two fastsense plots ----
    % addWidget('group', 'Label', 'Reactor Signals', ...)
    % InfoText: "Group wrapping the reactor pressure + temperature plots"
    grp = GroupWidget( ...
        'Label',       'Reactor Signals', ...
        'Mode',        'panel', ...
        'Description', 'GroupWidget wrapping reactor.pressure and reactor.temperature FastSense plots.', ...
        'Position',    [1 1 16 7]);

    % addWidget('fastsense', 'Tag', 'reactor.pressure', ...) -- second copy
    % InfoText: "Live reactor pressure (second copy, attached)"
    fsP = FastSenseWidget( ...
        'Title',       'Reactor Pressure', ...
        'Tag',         reactorPress, ...
        'Description', 'Attached second instance of reactor.pressure time series (Overview holds the pre-detached copy).', ...
        'Position',    [1 1 16 3]);

    % addWidget('fastsense', 'Tag', 'reactor.temperature', ...)
    % InfoText: "Live reactor temperature"
    fsT = FastSenseWidget( ...
        'Title',       'Reactor Temperature', ...
        'Tag',         reactorTemp, ...
        'Description', 'Live reactor.temperature time series (degC).', ...
        'Position',    [1 4 16 3]);
    grp.addChild(fsP);
    grp.addChild(fsT);
    engine.addWidget(grp);

    % ---- Gauge Tag reactor.rpm --------------------------------------
    % InfoText: "Reactor rpm gauge (arc style)"
    engine.addWidget('gauge', ...
        'Title',       'Reactor RPM', ...
        'Tag',         reactorRpm, ...
        'ValueFcn',    @() lastY_(reactorRpm), ...
        'Range',       [0 3000], ...
        'Units',       'rpm', ...
        'Style',       'arc', ...
        'Description', 'Arc gauge tracking the reactor rotor RPM.', ...
        'Position',    [17 1 7 4]);

    % ---- Collapsible 'Advanced' containing fastsense of rpm ---------
    % addWidget('collapsible', 'Label', 'Advanced', ...)
    % The WidgetTypeMap_ has no 'collapsible' kind; we build a GroupWidget
    % with Mode='collapsible' (which is exactly what engine.addCollapsible
    % does internally). Keep the plan's literal kind string in this
    % comment for grep-based verification.
    % InfoText: "Advanced collapsible -- RPM signal"
    fsRpm = FastSenseWidget( ...
        'Title',       'Reactor RPM (live)', ...
        'Tag',         reactorRpm, ...
        'Description', 'Live reactor.rpm time series; lives inside the Advanced collapsible.', ...
        'Position',    [1 1 24 3]);
    advCollapsible = engine.addCollapsible('Advanced', {fsRpm}, ...
        'Description', 'Collapsible section housing the reactor RPM time series. (Plan kind: addWidget(''collapsible'', ...).)', ...
        'Position', [1 8 24 4]);
    advCollapsible.Collapsed = false; %#ok<NASGU>

    % ---- Number reactor.temperature footer --------------------------
    % InfoText: "Current reactor temperature"
    engine.addWidget('number', ...
        'Title',       'Reactor Temp', ...
        'Tag',         reactorTemp, ...
        'ValueFcn',    @() lastY_(reactorTemp), ...
        'Units',       'degC', ...
        'Description', 'Current reactor temperature sample as a big number.', ...
        'Position',    [17 5 7 2]);
end

function v = lastY_(tag)
    v = NaN;
    try
        [~, y] = tag.getXY();
        if ~isempty(y), v = y(end); end
    catch
    end
end
