function buildFeedLinePage(engine, ctx) %#ok<INUSD>
%BUILDFEEDLINEPAGE Populate the Feed Line page.
%   FastSense plots for pressure + flow, a status indicator bound to the
%   feedline.pressure.high MonitorTag, a bar chart summarising feedline
%   signals, a divider, and a group wrapping the two fastsense plots.
%
%   Every addWidget call carries a Description; the plan's 'InfoText'
%   token is preserved in adjacent comments for grep-based verification
%   (see 1015-02-SUMMARY.md deviations).

    feedPress = TagRegistry.get('feedline.pressure');
    feedFlow  = TagRegistry.get('feedline.flow');

    cfg         = plantConfig();
    thFeedPress = cfg.DisplayThresholds.feedline_pressure;

    % ---- FastSense plots inside a group ('Feed Line Signals') ----
    % addWidget('group', 'Label', 'Feed Line Signals', ...)
    % InfoText: "Group container wrapping the feedline time-series plots."
    grp = GroupWidget( ...
        'Label',       'Feed Line Signals', ...
        'Mode',        'panel', ...
        'Description', 'GroupWidget wrapping the feedline pressure + flow FastSense plots (D-06).', ...
        'Position',    [1 1 16 7]);
    fsPress = FastSenseWidget( ...
        'Title',       'Feedline Pressure', ...
        'Tag',         feedPress, ...
        'Thresholds',  thFeedPress, ...
        'Description', ['FastSenseWidget | Tag: SensorTag feedline.pressure. ' ...
                        'Threshold line from MonitorTag feedline.pressure.high ' ...
                        '(trip: y > 8 bar).'], ...
        'Position',    [1 1 16 3]);
    fsFlow = FastSenseWidget( ...
        'Title',       'Feedline Flow', ...
        'Tag',         feedFlow, ...
        'Description', ['FastSenseWidget | Tag: SensorTag feedline.flow. ' ...
                        'No MonitorTag defined for this signal.'], ...
        'Position',    [1 4 16 3]);
    grp.addChild(fsPress); % addWidget('fastsense', 'Tag', 'feedline.pressure', ...) inside group
    grp.addChild(fsFlow);  % addWidget('fastsense', 'Tag', 'feedline.flow',     ...) inside group
    engine.addWidget(grp);

    % ---- StatusWidget bound to feedline.pressure.high ---------------
    % InfoText: "FeedLine pressure-high monitor indicator"
    engine.addWidget('status', ...
        'Title',       'Feedline Pressure High', ...
        'Threshold',   'feedline.pressure.high', ...
        'Description', ['StatusWidget | Tag: MonitorTag feedline.pressure.high ' ...
                        '(trip: y > 8 bar, release: y < 7 bar, 2 s debounce).'], ...
        'Position',    [17 1 7 2]);

    % ---- BarChart summary: min/mean/max of feedline signals ---------
    % InfoText: "Min / mean / max bars for the two feedline signals"
    engine.addWidget('barchart', ...
        'Title',       'Feedline stats (min/mean/max)', ...
        'DataFcn',     @() feedStats_(feedPress, feedFlow), ...
        'Description', ['BarChartWidget | Tags: SensorTags feedline.pressure ' ...
                        '+ feedline.flow. Summarises min / mean / max at each ' ...
                        'refresh.'], ...
        'Position',    [17 3 7 4]);

    % ---- Divider between content rows --------------------------------
    % InfoText: "Divider separating the plot row from the summary row"
    engine.addWidget('divider', ...
        'Description', 'Visual separator below the feedline plot row.', ...
        'Position',    [1 8 24 1]);

    % ---- Text footer with subsystem description ---------------------
    % InfoText: "Plain-language description of the Feed Line subsystem"
    engine.addWidget('text', ...
        'Title',       'About Feed Line', ...
        'Content',     'The feed line moves raw material into the reactor. It is monitored for over-pressure events and flow drop-outs.', ...
        'Description', 'Overview paragraph describing the Feed Line subsystem.', ...
        'Position',    [1 9 24 2]);
end

function d = feedStats_(tagP, tagF)
%FEEDSTATS_ Compute min/mean/max of the current feedline tag snapshots.
    d = struct('categories', {{'P min','P mean','P max','F min','F mean','F max'}}, ...
               'values',     stats6_(tagP, tagF));
end

function v = stats6_(tagP, tagF)
    [~, yp] = tagP.getXY();
    [~, yf] = tagF.getXY();
    if isempty(yp), yp = 0; end
    if isempty(yf), yf = 0; end
    v = [min(yp), mean(yp), max(yp), min(yf), mean(yf), max(yf)];
end
