function buildReactorPage(engine, ctx) %#ok<INUSD>
%BUILDREACTORPAGE Populate the Reactor page.
%   Second FastSense instance of reactor.pressure (no detach here, the
%   detached one lives on Overview), a fastsense for reactor.temperature,
%   a rpm gauge, and a collapsible sub-section with a fastsense for rpm.
%
%   Every addWidget carries a Description. The plan's 'InfoText' and
%   'collapsible' tokens are preserved in adjacent comments for the
%   grep-based verifier; the real kind 'collapsible' does not exist in
%   DashboardEngine.WidgetTypeMap_, so we use a GroupWidget with
%   Mode='collapsible' (that's exactly what engine.addCollapsible does).

    reactorPress = TagRegistry.get('reactor.pressure');
    reactorTemp  = TagRegistry.get('reactor.temperature');
    reactorRpm   = TagRegistry.get('reactor.rpm');

    cfg          = plantConfig();
    thPress      = cfg.DisplayThresholds.reactor_pressure;
    thTemp       = cfg.DisplayThresholds.reactor_temperature;

    % ---- Group 'Reactor Signals' wrapping the two fastsense plots ----
    grp = GroupWidget( ...
        'Label',       'Reactor Signals', ...
        'Mode',        'panel', ...
        'Description', 'GroupWidget wrapping reactor.pressure and reactor.temperature FastSense plots.', ...
        'Position',    [1 1 16 7]);

    fsP = FastSenseWidget( ...
        'Title',       'Reactor Pressure', ...
        'Tag',         reactorPress, ...
        'Thresholds',  thPress, ...
        'Description', ['FastSenseWidget | Tag: SensorTag reactor.pressure. ' ...
                        'Threshold line from MonitorTag reactor.pressure.critical ' ...
                        '(trip: y > 18 bar, release: y < 16 bar, 1 s debounce).'], ...
        'Position',    [1 1 16 3]);

    fsT = FastSenseWidget( ...
        'Title',       'Reactor Temperature', ...
        'Tag',         reactorTemp, ...
        'Thresholds',  thTemp, ...
        'Description', ['FastSenseWidget | Tag: SensorTag reactor.temperature. ' ...
                        'Threshold line from MonitorTag reactor.temperature.high ' ...
                        '(trip: y > 180 degC, release: y < 170 degC, 3 s debounce).'], ...
        'Position',    [1 4 16 3]);
    grp.addChild(fsP);
    grp.addChild(fsT);
    engine.addWidget(grp);

    % ---- Gauge Tag reactor.rpm --------------------------------------
    engine.addWidget('gauge', ...
        'Title',       'Reactor RPM', ...
        'Tag',         reactorRpm, ...
        'ValueFcn',    @() lastY_(reactorRpm), ...
        'Range',       [0 3000], ...
        'Units',       'rpm', ...
        'Style',       'arc', ...
        'Description', ['GaugeWidget | Tag: SensorTag reactor.rpm. ' ...
                        'No MonitorTag defined for this signal.'], ...
        'Position',    [17 1 7 4]);

    % ---- Collapsible 'Advanced' containing fastsense of rpm ---------
    fsRpm = FastSenseWidget( ...
        'Title',       'Reactor RPM (live)', ...
        'Tag',         reactorRpm, ...
        'Description', ['FastSenseWidget | Tag: SensorTag reactor.rpm. ' ...
                        'Housed in the Advanced collapsible below.'], ...
        'Position',    [1 1 24 3]);
    advCollapsible = engine.addCollapsible('Advanced', {fsRpm}, ...
        'Description', 'Collapsible section housing the reactor RPM time series.', ...
        'Position', [1 8 24 4]);
    advCollapsible.Collapsed = false; %#ok<NASGU>

    % ---- Number reactor.temperature footer --------------------------
    engine.addWidget('number', ...
        'Title',       'Reactor Temp', ...
        'Tag',         reactorTemp, ...
        'ValueFcn',    @() lastY_(reactorTemp), ...
        'Units',       'degC', ...
        'Description', ['NumberWidget | Tag: SensorTag reactor.temperature. ' ...
                        'Latest sample.'], ...
        'Position',    [17 5 7 2]);
end

function v = lastY_(tag)
    v = NaN;
    try
        [~, y] = tag.getXY();
        if ~isempty(y), v = y(end); end
    catch
    end
end
