classdef DashboardToolbar < handle
%DASHBOARDTOOLBAR Global toolbar for dashboard controls.
%
%   Provides buttons for: Live mode toggle, Edit mode, Save, Export.
%   Sits at the top of the dashboard figure.

    properties (Access = public)
        Height = 0.04
    end

    properties (SetAccess = private)
        hPanel       = []
        hLiveBtn     = []
        hEditBtn     = []
        hSaveBtn     = []
        hExportBtn   = []
        hTitleText   = []
        Engine       = []
    end

    methods
        function obj = DashboardToolbar(engine, hFigure, theme)
            obj.Engine = engine;

            obj.hPanel = uipanel('Parent', hFigure, ...
                'Units', 'normalized', ...
                'Position', [0, 1 - obj.Height, 1, obj.Height], ...
                'BorderType', 'none', ...
                'BackgroundColor', theme.ToolbarBackground);

            obj.hTitleText = uicontrol('Parent', obj.hPanel, ...
                'Style', 'text', ...
                'Units', 'normalized', ...
                'Position', [0.01 0.1 0.3 0.8], ...
                'String', engine.Name, ...
                'FontSize', theme.HeaderFontSize, ...
                'FontWeight', 'bold', ...
                'ForegroundColor', theme.ToolbarFontColor, ...
                'BackgroundColor', theme.ToolbarBackground, ...
                'HorizontalAlignment', 'left');

            btnW = 0.06;
            btnH = 0.7;
            btnY = 0.15;
            rightEdge = 0.99;

            rightEdge = rightEdge - btnW - 0.005;
            obj.hExportBtn = uicontrol('Parent', obj.hPanel, ...
                'Style', 'pushbutton', ...
                'Units', 'normalized', ...
                'Position', [rightEdge btnY btnW btnH], ...
                'String', 'Export', ...
                'Callback', @(~,~) obj.onExport());

            rightEdge = rightEdge - btnW - 0.005;
            obj.hSaveBtn = uicontrol('Parent', obj.hPanel, ...
                'Style', 'pushbutton', ...
                'Units', 'normalized', ...
                'Position', [rightEdge btnY btnW btnH], ...
                'String', 'Save', ...
                'Callback', @(~,~) obj.onSave());

            rightEdge = rightEdge - btnW - 0.005;
            obj.hEditBtn = uicontrol('Parent', obj.hPanel, ...
                'Style', 'pushbutton', ...
                'Units', 'normalized', ...
                'Position', [rightEdge btnY btnW btnH], ...
                'String', 'Edit', ...
                'Callback', @(~,~) obj.onEdit());

            rightEdge = rightEdge - btnW - 0.005;
            obj.hLiveBtn = uicontrol('Parent', obj.hPanel, ...
                'Style', 'togglebutton', ...
                'Units', 'normalized', ...
                'Position', [rightEdge btnY btnW btnH], ...
                'String', 'Live', ...
                'Value', 0, ...
                'Callback', @(src,~) obj.onLiveToggle(src));
        end

        function onLiveToggle(obj, src)
            if get(src, 'Value')
                obj.Engine.startLive();
            else
                obj.Engine.stopLive();
            end
        end

        function onSave(obj)
            [file, path] = uiputfile('*.json', 'Save Dashboard');
            if file ~= 0
                obj.Engine.save(fullfile(path, file));
            end
        end

        function onExport(obj)
            [file, path] = uiputfile('*.m', 'Export as Script');
            if file ~= 0
                obj.Engine.exportScript(fullfile(path, file));
            end
        end

        function onEdit(obj)
            disp('Edit mode not yet implemented (Phase 4)');
        end

        function contentArea = getContentArea(obj)
            contentArea = [0, 0, 1, 1 - obj.Height];
        end
    end
end
