classdef DashboardSerializer
%DASHBOARDSERIALIZER JSON load/save and .m export for dashboard configs.

    methods (Static)
        function save(config, filepath)
            %SAVE Write dashboard config struct to JSON file.
            %  Widgets may have heterogeneous fields, so encode each
            %  widget individually and assemble the JSON array by hand.
            parts = cell(1, numel(config.widgets));
            for i = 1:numel(config.widgets)
                parts{i} = jsonencode(config.widgets{i});
            end
            widgetsJson = ['[', strjoin(parts, ','), ']'];

            % Build top-level JSON without the widgets field
            topLevel = rmfield(config, 'widgets');
            topJson = jsonencode(topLevel);
            % Insert widgets array before the closing brace
            topJson = [topJson(1:end-1), ',"widgets":', widgetsJson, '}'];

            fid = fopen(filepath, 'w');
            if fid == -1
                error('DashboardSerializer:fileError', 'Cannot open file: %s', filepath);
            end
            fwrite(fid, topJson);
            fclose(fid);
        end

        function config = load(filepath)
            %LOAD Read dashboard config from JSON file.
            if ~exist(filepath, 'file')
                error('DashboardSerializer:fileNotFound', 'File not found: %s', filepath);
            end

            fid = fopen(filepath, 'r');
            jsonStr = fread(fid, '*char')';
            fclose(fid);

            config = jsondecode(jsonStr);

            % Ensure widgets is a cell array
            if isstruct(config.widgets)
                wa = config.widgets;
                config.widgets = cell(1, numel(wa));
                for i = 1:numel(wa)
                    config.widgets{i} = wa(i);
                end
            end
        end

        function config = widgetsToConfig(name, theme, liveInterval, widgets)
            %WIDGETSTOCONFIG Build a config struct from widget objects.
            config.name = name;
            config.theme = theme;
            config.liveInterval = liveInterval;
            config.grid = struct('columns', 12);
            config.widgets = cell(1, numel(widgets));
            for i = 1:numel(widgets)
                config.widgets{i} = widgets{i}.toStruct();
            end
        end

        function widgets = configToWidgets(config)
            %CONFIGTOWIDGETS Create widget objects from config struct.
            widgets = cell(1, numel(config.widgets));
            for i = 1:numel(config.widgets)
                ws = config.widgets{i};
                switch ws.type
                    case 'fastplot'
                        widgets{i} = FastPlotWidget.fromStruct(ws);
                    otherwise
                        error('DashboardSerializer:unknownType', ...
                            'Unknown widget type: %s', ws.type);
                end
            end
        end

        function exportScript(config, filepath)
            %EXPORTSCRIPT Generate a readable .m script from config.
            lines = {};
            lines{end+1} = sprintf('%% Dashboard: %s', config.name);
            lines{end+1} = sprintf('%% Auto-generated by DashboardSerializer.exportScript');
            lines{end+1} = sprintf('%% %s', datestr(now, 'yyyy-mm-dd HH:MM:SS'));
            lines{end+1} = '';
            lines{end+1} = sprintf('d = DashboardEngine(''%s'');', config.name);
            lines{end+1} = sprintf('d.Theme = ''%s'';', config.theme);
            lines{end+1} = sprintf('d.LiveInterval = %g;', config.liveInterval);
            lines{end+1} = '';

            for i = 1:numel(config.widgets)
                ws = config.widgets{i};
                pos = sprintf('[%d %d %d %d]', ws.position.col, ws.position.row, ...
                    ws.position.width, ws.position.height);

                switch ws.type
                    case 'fastplot'
                        if isfield(ws, 'source')
                            switch ws.source.type
                                case 'sensor'
                                    lines{end+1} = sprintf('d.addWidget(''fastplot'', ''Title'', ''%s'', ...', ws.title);
                                    lines{end+1} = sprintf('    ''Position'', %s, ...', pos);
                                    lines{end+1} = sprintf('    ''Sensor'', SensorRegistry.get(''%s''));', ws.source.name);
                                case 'file'
                                    lines{end+1} = sprintf('d.addWidget(''fastplot'', ''Title'', ''%s'', ...', ws.title);
                                    lines{end+1} = sprintf('    ''Position'', %s, ...', pos);
                                    lines{end+1} = sprintf('    ''File'', ''%s'', ''XVar'', ''%s'', ''YVar'', ''%s'');', ...
                                        ws.source.path, ws.source.xVar, ws.source.yVar);
                                case 'data'
                                    lines{end+1} = sprintf('d.addWidget(''fastplot'', ''Title'', ''%s'', ...', ws.title);
                                    lines{end+1} = sprintf('    ''Position'', %s, ...', pos);
                                    lines{end+1} = sprintf('    ''XData'', %s, ''YData'', %s);', ...
                                        mat2str(ws.source.x), mat2str(ws.source.y));
                                otherwise
                                    lines{end+1} = sprintf('d.addWidget(''fastplot'', ''Title'', ''%s'', ''Position'', %s);', ws.title, pos);
                            end
                        else
                            lines{end+1} = sprintf('d.addWidget(''fastplot'', ''Title'', ''%s'', ''Position'', %s);', ws.title, pos);
                        end
                    otherwise
                        lines{end+1} = sprintf('d.addWidget(''%s'', ''Title'', ''%s'', ''Position'', %s);', ws.type, ws.title, pos);
                end
                lines{end+1} = '';
            end

            lines{end+1} = 'd.render();';

            fid = fopen(filepath, 'w');
            if fid == -1
                error('DashboardSerializer:fileError', 'Cannot open file: %s', filepath);
            end
            fprintf(fid, '%s\n', lines{:});
            fclose(fid);
        end
    end
end
