%DEMO_TOOLBAR_REWORK Demo for the reworked dashboard toolbar.
%
%   Exercises the three new toolbar behaviors:
%     1. Info button is always present (even with no InfoFile). Click it
%        to see the built-in placeholder page.
%     2. Click Live — the Live button gets a solid blue border. Click
%        again to turn it off; border reverts.
%     3. Hover any button — all now carry tooltips.
%
%   Usage:
%     >> run('examples/demo_toolbar_rework.m')

close all force;

d = DashboardEngine('Toolbar Rework Demo', 'LiveInterval', 1.0);

% Live-friendly widget: the number updates each live tick.
d.addWidget('number', ...
    'Title',    'Random value', ...
    'Position', [1 1 6 3], ...
    'ValueFcn', @() randn(), ...
    'Format',   '%.3f');

d.addWidget('text', ...
    'Title',    'Instructions', ...
    'Position', [1 4 10 4], ...
    'Content',  sprintf([ ...
        '**Try the toolbar:**\n\n', ...
        '1. Hover every button -- each shows a tooltip.\n\n', ...
        '2. Click **Live** -- button gets a solid blue border and the ', ...
        'Random value updates each second. Click again to stop.\n\n', ...
        '3. Click **Info** -- opens a built-in placeholder page ', ...
        '(no InfoFile was configured on this dashboard).']));

d.render();
disp('Demo ready. Try Live + Info buttons, hover for tooltips.');
