%DEMO_TOOLBAR_REWORK Demo for the reworked dashboard toolbar.
%
%   Exercises the toolbar + config + stale-banner behaviors:
%     1. Info button is always present — click it with no InfoFile set
%        to see the built-in placeholder page.
%     2. Config button opens a dialog for every public engine property
%        (Name, Theme, LiveInterval, InfoFile, ProgressMode,
%        ShowTimePanel). Hover each field for its tooltip. Use Browse…
%        next to InfoFile to pick a Markdown file. Apply to commit.
%     3. Live button gets a solid blue border when toggled on.
%     4. Stale-data banner lists EVERY widget whose data is not advancing.
%        Three frozen sensors here — click Live and the banner names all
%        three after one LiveInterval. Click the X on the banner to
%        dismiss it (reappears when data flows then stops again).
%
%   Usage:
%     >> run('examples/demo_toolbar_rework.m')

close all force;

% Three pre-seeded sensors with fixed time ranges — during live mode,
% none of them advance, so the stale-data banner will list all three.
nSeed = 200;
tSeed = linspace(-20, 0, nSeed);

sTemp  = SensorTag('DEMO-T', 'Name', 'Temperature', 'Units', 'C', ...
    'X', tSeed, 'Y', 20 + sin(2*pi*tSeed/10) + randn(1, nSeed)*0.3);
sPress = SensorTag('DEMO-P', 'Name', 'Pressure', 'Units', 'psi', ...
    'X', tSeed, 'Y', 50 + 5*sin(2*pi*tSeed/15) + randn(1, nSeed)*1.0);
sFlow  = SensorTag('DEMO-F', 'Name', 'Flow Rate', 'Units', 'L/min', ...
    'X', tSeed, 'Y', max(0, 120 + 8*sin(2*pi*tSeed/8) + randn(1, nSeed)*2.0));

d = DashboardEngine('Toolbar Rework Demo', 'LiveInterval', 2.0);

d.addWidget('fastsense', ...
    'Title',    'Temperature', ...
    'Position', [1 1 6 3], ...
    'Tag',      sTemp);

d.addWidget('fastsense', ...
    'Title',    'Pressure', ...
    'Position', [7 1 6 3], ...
    'Tag',      sPress);

d.addWidget('fastsense', ...
    'Title',    'Flow Rate', ...
    'Position', [1 4 6 3], ...
    'Tag',      sFlow);

d.addWidget('number', ...
    'Title',    'Random (no time data)', ...
    'Position', [7 4 6 2], ...
    'ValueFcn', @() randn(), ...
    'Format',   '%.3f');

d.addWidget('text', ...
    'Title',    'Instructions', ...
    'Position', [1 7 12 3], ...
    'Content',  sprintf([ ...
        '**Try the toolbar:**\n\n', ...
        '1. Click **Live** — blue border appears. After ~2s the amber ', ...
        'banner names all three frozen sensors (Temperature, Pressure, ', ...
        'Flow Rate). The Random widget is skipped because it has no ', ...
        'time-series data.\n\n', ...
        '2. Click **X** on the banner — it hides. Stop and re-start Live ', ...
        'to see it come back.\n\n', ...
        '3. Click **Config** for settings, **Info** for the placeholder page.']));

d.render();
disp('Demo ready — click Live and wait ~2s for the multi-sensor stale banner.');
