%% Dashboard Engine — All Widget Types Demo
% Demonstrates every widget type in a single dashboard:
%   FastPlot, KPI, Status, Text, Gauge, Table, RawAxes, EventTimeline
%
% Usage:
%   example_dashboard_all_widgets
%
% Click "Edit" in the toolbar to enter GUI builder mode (Phase 4).

close all force;
clear functions;  % flush MATLAB function cache

% Use this project's setup (not worktree copies)
projectRoot = fileparts(fileparts(mfilename('fullpath')));
run(fullfile(projectRoot, 'setup.m'));

%% Generate sample process data
t = linspace(0, 86400, 10000);  % 24 hours in seconds
temp = 70 + 5*sin(2*pi*t/3600) + randn(1,10000)*0.5;
pressure = 50 + 20*sin(2*pi*t/7200) + randn(1,10000)*1.0;

%% Create dashboard
d = DashboardEngine('Process Monitoring — All Widgets');
d.Theme = 'light';
d.LiveInterval = 5;

% Diagnostic: verify theme is applied
themeCheck = DashboardTheme('light');
fprintf('DEBUG theme: %s | DashboardBG=[%.2f %.2f %.2f]\n', ...
    d.Theme, themeCheck.DashboardBackground);
fprintf('DEBUG DashboardTheme.m: %s\n', which('DashboardTheme'));
fprintf('DEBUG DashboardEngine.m: %s\n', which('DashboardEngine'));

% --- Row 1: Header + KPIs + Status indicators ---
d.addWidget('text', 'Title', 'Overview', ...
    'Position', [1 1 2 1], ...
    'Content', 'Line 4 — Shift A', ...
    'FontSize', 16, ...
    'Alignment', 'left');

d.addWidget('kpi', 'Title', 'Temperature', ...
    'Position', [3 1 2 1], ...
    'Units', [char(176) 'F'], ...
    'Format', '%.1f', ...
    'StaticValue', temp(end));

d.addWidget('kpi', 'Title', 'Pressure', ...
    'Position', [5 1 2 1], ...
    'Units', 'psi', ...
    'Format', '%.0f', ...
    'StaticValue', pressure(end));

d.addWidget('status', 'Title', 'Temp Status', ...
    'Position', [7 1 2 1], ...
    'StaticStatus', 'ok');

d.addWidget('status', 'Title', 'Pressure', ...
    'Position', [9 1 2 1], ...
    'StaticStatus', 'warning');

d.addWidget('gauge', 'Title', 'Load', ...
    'Position', [11 1 2 2], ...
    'Range', [0 100], ...
    'Units', '%', ...
    'StaticValue', 73);

% --- Row 2: Main time-series plots ---
d.addWidget('fastplot', 'Title', 'Temperature Trend', ...
    'Position', [1 2 6 3], ...
    'XData', t, 'YData', temp);

d.addWidget('fastplot', 'Title', 'Pressure Trend', ...
    'Position', [7 2 4 3], ...
    'XData', t, 'YData', pressure);

% --- Row 5: Table + RawAxes + Timeline ---
d.addWidget('table', 'Title', 'Alarm Log', ...
    'Position', [1 5 4 2], ...
    'ColumnNames', {'Time', 'Tag', 'Value', 'Status'}, ...
    'Data', {'08:15', 'T-401', '82.3', 'Warning'; ...
             '09:42', 'P-201', '71.0', 'OK'; ...
             '11:03', 'T-401', '86.1', 'Alarm'; ...
             '14:27', 'P-201', '68.5', 'OK'});

d.addWidget('rawaxes', 'Title', 'Temperature Histogram', ...
    'Position', [5 5 4 2], ...
    'PlotFcn', @(ax) histogram(ax, temp, 50, ...
        'FaceColor', [0.31 0.80 0.64], 'EdgeColor', 'none'));

events = struct('startTime', {0,   18000, 39600, 72000}, ...
                'endTime',   {3600, 21600, 43200, 79200}, ...
                'label',     {'High Temp', 'Normal', 'High Temp', 'Normal'});
d.addWidget('timeline', 'Title', 'Event Timeline', ...
    'Position', [1 7 12 2], ...
    'Events', events);

%% Render
d.render();

fprintf('Dashboard rendered with %d widgets.\n', numel(d.Widgets));
fprintf('Click "Edit" to enter GUI builder mode.\n');
fprintf('Click "Save" to export as JSON, "Export" to generate .m script.\n');
