function t = midnight()
%MIDNIGHT A deep blue-black custom theme for FastPlot.
    t = struct( ...
        'Background',      [0.05 0.05 0.15], ...
        'AxesColor',       [0.08 0.08 0.2], ...
        'ForegroundColor', [0.8 0.8 0.9], ...
        'GridColor',       [0.3 0.3 0.5], ...
        'GridAlpha',       0.3, ...
        'GridStyle',       ':', ...
        'FontName',        'Helvetica', ...
        'FontSize',        10, ...
        'TitleFontSize',   12, ...
        'LineWidth',       1.0, ...
        'LineColorOrder',  'vibrant', ...
        'ThresholdColor',  [1 0.3 0.3], ...
        'ThresholdStyle',  '--', ...
        'ViolationMarker', 'o', ...
        'ViolationSize',   4, ...
        'BandAlpha',       0.2 ...
    );
end
