%% Mushroom Cards Demo — IconCardWidget, ChipBarWidget, SparklineCardWidget
% Demonstrates all three mushroom card widget types added in Phase 999.1:
%
%   Widget 1: IconCardWidget   — Compact state-colored KPI card with icon circle
%   Widget 2: ChipBarWidget    — Horizontal row of mini status chips
%   Widget 3: SparklineCardWidget — KPI card with inline sparkline trend chart
%
% Binding modes covered per widget type:
%   IconCardWidget     — Sensor binding, StaticValue, ValueFcn, StaticState
%                        (ok / warn / alarm / info / inactive), IconColor, Format
%   ChipBarWidget      — sensor chips, statusFcn chips, iconColor chips, Description
%   SparklineCardWidget — Sensor binding, StaticValue + SparkData, NSparkPoints,
%                        SparkColor, ShowDelta, DeltaFormat, Description
%
% Usage:
%   example_mushroom_cards
%
% After render you will see:
%   Row 1  — Three IconCardWidget examples (sensor-bound, static, callback)
%   Row 3  — ChipBarWidget with 6 chips using all three binding modes
%   Row 4  — Three SparklineCardWidget examples (sensor, static+history, sensor+delta)
%   Row 7  — Divider separator
%   Row 8  — Three more IconCardWidget instances showing alarm/info/inactive states

close all force;
clear functions;  % flush MATLAB function cache

projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
run(fullfile(projectRoot, 'install.m'));

%% ========== Generate realistic process data ==========
rng(42);  % reproducible
N = 5000;
t = linspace(0, 86400, N);  % 24 hours in seconds

% --- Machine mode state channel (idle=0, running=1, maintenance=2) ---
modeChangeTimes = [0, 3600, 7200, 28800, 36000, 72000, 79200, 82800];
modeValues      = [0, 1,    1,    2,     1,     0,     1,     1];

scMode = StateTag('machine', 'X', modeChangeTimes, 'Y', modeValues);

% --- Temperature sensor T-401 ---
tempBase = zeros(1, N);
for k = 1:N
    mode = scMode.valueAt(t(k));
    switch mode
        case 0, tempBase(k) = 68;
        case 1, tempBase(k) = 74;
        case 2, tempBase(k) = 65;
    end
end
tempNoise = 3 * sin(2*pi*t/3600) + randn(1, N) * 1.2;
temp = tempBase + tempNoise;

sTemp = SensorTag('T-401', 'Name', 'Temperature', 'Units', [char(176) 'F'], 'X', t, 'Y', temp);


% --- Pressure sensor P-201 ---
pressBase = zeros(1, N);
for k = 1:N
    mode = scMode.valueAt(t(k));
    switch mode
        case 0, pressBase(k) = 30;
        case 1, pressBase(k) = 55;
        case 2, pressBase(k) = 20;
    end
end
pressNoise = 8 * sin(2*pi*t/7200) + randn(1, N) * 2;
pressure = pressBase + pressNoise;

sPress = SensorTag('P-201', 'Name', 'Pressure', 'Units', 'psi', 'X', t, 'Y', pressure);


%% ========== Create DashboardEngine ==========
% Dark theme contrasts nicely with the state-colored icon circles.
d = DashboardEngine('Mushroom Cards Demo', 'Theme', 'dark');

%% ========== Row 1 — IconCardWidget showcase (columns 1-24, row 1) ==========

% 1a. Sensor-bound: reads latest value and derives state from threshold rules
d.addWidget('iconcard', ...
    'Title', 'Temperature', ...
    'Tag', sTemp, ...
    'Units', [char(176) 'F'], ...
    'SecondaryLabel', 'Sensor T-401', ...
    'Description', 'Live temperature from T-401. Icon color reflects alarm state.', ...
    'Position', [1 1 8 2]);

% 1b. StaticValue + StaticState + IconColor: completely static KPI, custom icon color
d.addWidget('iconcard', ...
    'Title', 'Pump Status', ...
    'StaticValue', 98.5, ...
    'Units', '%', ...
    'StaticState', 'ok', ...
    'Format', '%.0f', ...
    'IconColor', [0.2 0.8 0.4], ...
    'SecondaryLabel', 'Uptime', ...
    'Description', 'Static pump uptime KPI with explicit ok state and green icon override.', ...
    'Position', [9 1 8 2]);

% 1c. ValueFcn: callback-driven value resolved on each refresh
d.addWidget('iconcard', ...
    'Title', 'Memory', ...
    'ValueFcn', @() struct('value', 67.3, 'unit', '%'), ...
    'StaticState', 'warn', ...
    'SecondaryLabel', 'Server RAM', ...
    'Description', 'Callback-driven memory usage. ValueFcn returns struct with .value and .unit fields.', ...
    'Position', [17 1 8 2]);

%% ========== Row 2 — ChipBarWidget showcase (full width, row 3) ==========
% Manually construct to set the Chips property directly — demonstrates all
% three chip binding modes: sensor, statusFcn, and fixed iconColor.
w = ChipBarWidget('Title', 'System Health');
w.Chips = { ...
    struct('label', 'Temp',    'sensor',    sTemp), ...
    struct('label', 'Pressure', 'sensor',   sPress), ...
    struct('label', 'Pump',    'statusFcn', @() 'ok'), ...
    struct('label', 'Fan',     'statusFcn', @() 'warn'), ...
    struct('label', 'Network', 'statusFcn', @() 'alarm'), ...
    struct('label', 'Custom',  'iconColor', [0.4 0.2 0.9]) ...
};
w.Position    = [1 3 24 1];
w.Description = 'System health at a glance — sensor-bound, callback-bound, and fixed-color chips.';
d.addWidget(w);

%% ========== Row 3 — SparklineCardWidget showcase (columns 1-24, row 4) ==========

% 3a. Sensor binding: sparkline uses Sensor.Y tail, delta derived automatically
d.addWidget('sparkline', ...
    'Title', 'Temperature', ...
    'Tag', sTemp, ...
    'Units', [char(176) 'F'], ...
    'NSparkPoints', 80, ...
    'SparkColor', [1 0.4 0.2], ...
    'Description', 'Temperature trend with 80-point sparkline tail.', ...
    'Position', [1 4 8 3]);

% 3b. StaticValue + SparkData: pre-computed history vector with delta enabled
sparkHist = 40 + 15 * sin(linspace(0, 4*pi, 100)) + cumsum(randn(1, 100)) * 0.5;
d.addWidget('sparkline', ...
    'Title', 'CPU Load', ...
    'StaticValue', sparkHist(end), ...
    'SparkData', sparkHist, ...
    'Units', '%', ...
    'Format', '%.0f', ...
    'ShowDelta', true, ...
    'DeltaFormat', '%+.0f', ...
    'Description', 'Synthetic CPU history loaded from a static vector. ShowDelta highlights trend direction.', ...
    'Position', [9 4 8 3]);

% 3c. Sensor binding (pressure) with delta indicator and custom NSparkPoints
d.addWidget('sparkline', ...
    'Title', 'Pressure', ...
    'Tag', sPress, ...
    'Units', 'psi', ...
    'NSparkPoints', 50, ...
    'ShowDelta', true, ...
    'Description', 'Pressure trend with 50-point sparkline and delta indicator.', ...
    'Position', [17 4 8 3]);

%% ========== Row 4 — Divider + more IconCardWidget states (rows 7-9) ==========

% Visual separator
d.addWidget('divider', 'Position', [1 7 24 1]);

% Additional IconCardWidget instances showing every remaining StaticState value
d.addWidget('iconcard', ...
    'Title', 'Fire Alarm', ...
    'StaticValue', 1, ...
    'Format', '%.0f', ...
    'StaticState', 'alarm', ...
    'Units', 'active', ...
    'SecondaryLabel', 'Zone 3', ...
    'Description', 'Alarm state — icon renders in theme alarm color (red).', ...
    'Position', [1 8 8 2]);

d.addWidget('iconcard', ...
    'Title', 'Firmware', ...
    'StaticValue', 3.2, ...
    'Format', 'v%.1f', ...
    'StaticState', 'info', ...
    'SecondaryLabel', 'Latest version', ...
    'Description', 'Info state — icon renders in theme info color (blue).', ...
    'Position', [9 8 8 2]);

d.addWidget('iconcard', ...
    'Title', 'Offline', ...
    'StaticValue', 0, ...
    'Format', '%.0f', ...
    'StaticState', 'inactive', ...
    'Units', 'devices', ...
    'SecondaryLabel', 'All connected', ...
    'Description', 'Inactive state — icon renders in neutral gray.', ...
    'Position', [17 8 8 2]);

%% ========== Render ==========
d.render();

%% ========== Summary ==========
fprintf('\n=== Mushroom Cards Demo rendered ===\n');
fprintf('\n--- Widget types demonstrated ---\n');
fprintf('  IconCardWidget\n');
fprintf('    Sensor binding      — live value + state derived from threshold rules\n');
fprintf('    StaticValue         — fixed numeric value with explicit StaticState\n');
fprintf('    ValueFcn            — callback returning scalar or struct(.value, .unit)\n');
fprintf('    StaticState values  — ok / warn / alarm / info / inactive\n');
fprintf('    IconColor override  — explicit [r g b] bypasses state-based color lookup\n');
fprintf('    Units / Format      — unit suffix and sprintf format customisation\n');
fprintf('    SecondaryLabel      — subtitle text below primary value\n');
fprintf('\n  ChipBarWidget\n');
fprintf('    sensor chips        — Chip.sensor drives color from threshold state\n');
fprintf('    statusFcn chips     — Chip.statusFcn returns state string each refresh\n');
fprintf('    iconColor chips     — Chip.iconColor fixed [r g b] bypasses state\n');
fprintf('    Description tooltip — visible via info icon in widget header\n');
fprintf('\n  SparklineCardWidget\n');
fprintf('    Sensor binding      — Sensor.Y tail used for value + sparkline data\n');
fprintf('    StaticValue+SparkData — separate static value and history vector\n');
fprintf('    NSparkPoints        — 80-pt (temp) and 50-pt (pressure) tail window\n');
fprintf('    SparkColor          — explicit sparkline line color override\n');
fprintf('    ShowDelta / DeltaFormat — trend arrow and formatted delta label\n');
