function theme = FastPlotTheme(preset, varargin)
%FASTPLOTTHEME Return a theme struct for FastPlot styling.
%   theme = FASTPLOTTHEME() returns the 'default' theme preset.
%
%   theme = FASTPLOTTHEME(preset) returns the named preset. Valid preset
%   names are 'default', 'dark', 'light', 'industrial', and 'scientific'.
%
%   theme = FASTPLOTTHEME(preset, Name, Value) returns the named preset
%   with individual fields overridden by the supplied name-value pairs.
%
%   theme = FASTPLOTTHEME(S) where S is a struct uses S as a set of
%   overrides on top of the 'default' preset. Missing fields are filled
%   from 'default'.
%
%   Inputs:
%     preset   — char or struct; a preset name ('default', 'dark',
%                'light', 'industrial', 'scientific') or a partial struct
%                of theme fields to merge onto the default (optional,
%                default: 'default')
%     varargin — name-value pairs of theme fields to override after
%                the preset is loaded (optional)
%
%   Output:
%     theme — struct with the following fields:
%       Background      — 1x3 RGB; figure background color
%       AxesColor       — 1x3 RGB; axes background color
%       ForegroundColor — 1x3 RGB; text and tick color
%       GridColor       — 1x3 RGB; grid line color
%       GridAlpha       — double in [0,1]; grid transparency
%       GridStyle       — char; grid line style ('-', ':', '--', 'none')
%       FontName        — char; font family name
%       FontSize        — double; axes label font size in points
%       TitleFontSize   — double; title font size in points
%       LineWidth       — double; default line width in points
%       LineColorOrder  — Nx3 RGB matrix or palette name ('vibrant',
%                         'muted', 'colorblind'); resolved to Nx3 before
%                         return
%       ThresholdColor  — 1x3 RGB; color for threshold lines
%       ThresholdStyle  — char; threshold line style
%       ViolationMarker — char; marker symbol for violation points
%       ViolationSize   — double; marker size for violations in points
%       BandAlpha       — double in [0,1]; transparency of shaded bands
%
%   Example:
%     theme = FastPlotTheme('dark', 'FontSize', 14, 'LineWidth', 1.5);
%
%   Example — struct override:
%     overrides.FontSize = 14;
%     overrides.GridAlpha = 0.5;
%     theme = FastPlotTheme(overrides);
%
%   See also FastPlotDefaults, getDefaults.

    if nargin == 0
        preset = 'default';
    end

    % If preset is already a struct, use it as base
    if isstruct(preset)
        theme = mergeTheme(getPreset('default'), preset);
    else
        theme = getPreset(preset);
    end

    % Apply name-value overrides
    for k = 1:2:numel(varargin)
        theme.(varargin{k}) = varargin{k+1};
    end

    % Resolve named palettes to Nx3 matrices
    if ischar(theme.LineColorOrder)
        theme.LineColorOrder = getPalette(theme.LineColorOrder);
    end
end

function t = getPreset(name)
%GETPRESET Return a complete theme struct for the named preset.
%   t = getPreset(name) returns a struct containing all theme fields
%   populated with values appropriate for the requested visual style.
%
%   Input:
%     name — char; one of 'default', 'dark', 'light', 'industrial',
%            'scientific' (case-insensitive)
%
%   Output:
%     t — struct; fully populated theme (see FastPlotTheme for fields)
%
%   Throws FastPlotTheme:unknownPreset if the name is not recognized.
    switch lower(name)
        case 'default'
            t = struct( ...
                'Background',      [1 1 1], ...
                'AxesColor',       [1 1 1], ...
                'ForegroundColor', [0.15 0.15 0.15], ...
                'GridColor',       [0.15 0.15 0.15], ...
                'GridAlpha',       0.15, ...
                'GridStyle',       '-', ...
                'FontName',        'Helvetica', ...
                'FontSize',        10, ...
                'TitleFontSize',   12, ...
                'LineWidth',       1.0, ...
                'LineColorOrder',  'vibrant', ...
                'ThresholdColor',  [0.8 0 0], ...
                'ThresholdStyle',  '--', ...
                'ViolationMarker', 'o', ...
                'ViolationSize',   4, ...
                'BandAlpha',       0.15 ...
            );
        case 'dark'
            t = struct( ...
                'Background',      [0.1 0.1 0.12], ...
                'AxesColor',       [0.15 0.15 0.18], ...
                'ForegroundColor', [0.85 0.85 0.85], ...
                'GridColor',       [0.35 0.35 0.35], ...
                'GridAlpha',       0.4, ...
                'GridStyle',       ':', ...
                'FontName',        'Helvetica', ...
                'FontSize',        10, ...
                'TitleFontSize',   12, ...
                'LineWidth',       1.0, ...
                'LineColorOrder',  'vibrant', ...
                'ThresholdColor',  [1 0.3 0.3], ...
                'ThresholdStyle',  '--', ...
                'ViolationMarker', 'o', ...
                'ViolationSize',   4, ...
                'BandAlpha',       0.2 ...
            );
        case 'light'
            t = struct( ...
                'Background',      [0.98 0.98 0.98], ...
                'AxesColor',       [1 1 1], ...
                'ForegroundColor', [0.25 0.25 0.25], ...
                'GridColor',       [0.8 0.8 0.8], ...
                'GridAlpha',       0.3, ...
                'GridStyle',       '-', ...
                'FontName',        'Helvetica', ...
                'FontSize',        10, ...
                'TitleFontSize',   12, ...
                'LineWidth',       1.0, ...
                'LineColorOrder',  'muted', ...
                'ThresholdColor',  [0.7 0 0], ...
                'ThresholdStyle',  '--', ...
                'ViolationMarker', 'o', ...
                'ViolationSize',   4, ...
                'BandAlpha',       0.12 ...
            );
        case 'industrial'
            t = struct( ...
                'Background',      [0.95 0.95 0.92], ...
                'AxesColor',       [1 1 0.97], ...
                'ForegroundColor', [0.1 0.1 0.1], ...
                'GridColor',       [0.6 0.6 0.55], ...
                'GridAlpha',       0.3, ...
                'GridStyle',       '-', ...
                'FontName',        'Consolas', ...
                'FontSize',        10, ...
                'TitleFontSize',   13, ...
                'LineWidth',       1.2, ...
                'LineColorOrder',  'vibrant', ...
                'ThresholdColor',  [0.9 0 0], ...
                'ThresholdStyle',  '--', ...
                'ViolationMarker', 'o', ...
                'ViolationSize',   5, ...
                'BandAlpha',       0.18 ...
            );
        case 'scientific'
            t = struct( ...
                'Background',      [1 1 1], ...
                'AxesColor',       [1 1 1], ...
                'ForegroundColor', [0 0 0], ...
                'GridColor',       [0 0 0], ...
                'GridAlpha',       0, ...
                'GridStyle',       'none', ...
                'FontName',        'Times New Roman', ...
                'FontSize',        11, ...
                'TitleFontSize',   13, ...
                'LineWidth',       0.75, ...
                'LineColorOrder',  'colorblind', ...
                'ThresholdColor',  [0.6 0 0], ...
                'ThresholdStyle',  '--', ...
                'ViolationMarker', 'o', ...
                'ViolationSize',   3, ...
                'BandAlpha',       0.1 ...
            );
        otherwise
            error('FastPlotTheme:unknownPreset', ...
                'Unknown theme preset: ''%s''. Use ''default'', ''dark'', ''light'', ''industrial'', or ''scientific''.', name);
    end
end

function colors = getPalette(name)
%GETPALETTE Return an Nx3 RGB color matrix for the named palette.
%   colors = getPalette(name) returns an 8x3 matrix of RGB triplets
%   for the requested color palette.
%
%   Input:
%     name — char; one of 'vibrant', 'muted', 'colorblind'
%            (case-insensitive). The 'colorblind' palette follows the
%            Wong (2011) colorblind-safe palette.
%
%   Output:
%     colors — 8x3 double; each row is an [R G B] triplet in [0,1]
%
%   Throws FastPlotTheme:unknownPalette if the name is not recognized.
    switch lower(name)
        case 'vibrant'
            colors = [ ...
                0.00 0.45 0.74; ...  % blue
                0.85 0.33 0.10; ...  % red-orange
                0.93 0.69 0.13; ...  % yellow
                0.49 0.18 0.56; ...  % purple
                0.47 0.67 0.19; ...  % green
                0.30 0.75 0.93; ...  % cyan
                0.64 0.08 0.18; ...  % dark red
                0.00 0.62 0.45; ...  % teal
            ];
        case 'muted'
            colors = [ ...
                0.33 0.47 0.64; ...  % steel blue
                0.68 0.40 0.36; ...  % dusty rose
                0.55 0.55 0.36; ...  % olive
                0.58 0.44 0.65; ...  % mauve
                0.45 0.62 0.50; ...  % sage
                0.65 0.55 0.40; ...  % tan
                0.40 0.55 0.60; ...  % slate
                0.62 0.42 0.52; ...  % plum
            ];
        case 'colorblind'
            % Wong (2011) colorblind-safe palette
            colors = [ ...
                0.00 0.45 0.70; ...  % blue
                0.90 0.62 0.00; ...  % orange
                0.00 0.62 0.45; ...  % bluish green
                0.80 0.47 0.65; ...  % reddish purple
                0.94 0.89 0.26; ...  % yellow
                0.34 0.71 0.91; ...  % sky blue
                0.84 0.37 0.00; ...  % vermillion
                0.00 0.00 0.00; ...  % black
            ];
        otherwise
            error('FastPlotTheme:unknownPalette', ...
                'Unknown palette: ''%s''. Use ''vibrant'', ''muted'', or ''colorblind''.', name);
    end
end

function result = mergeTheme(base, overrides)
%MERGETHEME Merge override fields onto a base theme struct.
%   result = mergeTheme(base, overrides) copies every field from
%   overrides into base, replacing existing values or adding new ones.
%   Fields present in base but absent from overrides are preserved.
%
%   Inputs:
%     base      — struct; complete theme to use as the starting point
%     overrides — struct; partial theme whose fields take precedence
%
%   Output:
%     result — struct; merged theme with the same field set as base
%              plus any additional fields from overrides
    result = base;
    fnames = fieldnames(overrides);
    for i = 1:numel(fnames)
        result.(fnames{i}) = overrides.(fnames{i});
    end
end
